### ISSUE TITLE
Remove need of child process

### ISSUE THREAD

**Issue by psychon** [stefano-m/awesome-pulseaudio_widget#1]
Hi, I found your library through luarocks.org. Are you perhaps interested in adding it to https://awesomewm.org/recipes/? (see https://github.com/awesomeWM/awesome-www#contributing-to-recipes-section)

Anyway, to explain why I am opening this issue I'll first explain my understanding on how this widget currently works:
- `pulseaudio_widget_client.lua` is a Lua program that watches for PulseAudio state changes via DBus. It uses LGI and Gio's DBus bindings to do this. Each event is formatted as a string and printed to stdout.
- `pulseaudo_widget.lua` uses the `awful.spawn.with_line_callback` API to start the above process, read its output, and react to it.

My question is: Why does this have to be split into two parts like this? Awesome uses a GLib-based main loop, just like your `pulseaudio_widget_client.lua` (last line of the file: `GLib.MainLoop():run()`. So, all your DBus bindings should "just work" inside of awesome and you should be able to merge the two files into one. That should also simplify the code a bit, since you do not have to serialize events into a string and parse that one again.

Am I missing something or could the above work?

Thanks,
Uli

Edit: Perhaps to be a little clearer what I mean: Remove the last line (`GLib.MainLoop():run()`) from `pulseaudio_widget_client.lua` and run `awesome-client 'dofile("/path/to/pulseaudio_widget_client.lua")`. Now, watch what happens on awesome's stdout.

**Comment by stefano-m** [comment]
Hi and thanks for your interest in the pulseaudio widget!

I was not aware that one could use Awesome's internal mail loop to run other GLib code. The reason why there is an external client script is that I could not find a way to use Awesome's own DBus API as it only accepts sytem and session buses. Pulseaudio unfortunately does not work like that.

Would you be interested in submitting a pull request to make the external script redundant?

Thanks!

**Comment by psychon** [comment]
> I could not find a way to use Awesome's own DBus API as it only accepts sytem and session buses.

Yup, awesome's built-in DBus API is quite limited and ugly.

> Would you be interested in submitting a pull request to make the external script redundant?

Interested, sure. But time would be the limiting factor, meaning that it might take quite a while (or even forever) before I get this done.
I opened this issue mostly to let you know about the possibility.

**Comment by stefano-m** [comment]
Thanks for your feedback. My time is limited as well, but maybe between the two of us we could get something done before the end of the century 😉 
I'll try and have a look into it too.

**Comment by psychon** [comment]
Here is a completely untested (don't have the needed dependencies) hack that gets rid of the child process without getting rid of the string parsing: https://gist.github.com/psychon/5e5775df8eb7fb1359c0e8b7883fb7a0

The same patch with `git diff -w` so that whitespace-changes are not displayed:
```diff
diff --git a/README.md b/README.md
index 2fcf6da..d1cb775 100644
--- a/README.md
+++ b/README.md
@@ -4,18 +4,6 @@ A widget for the Awesome Window Manager (version 4.x) that
 uses [pulseaudio_dbus](https://github.com/stefano-m/lua-pulseaudio_dbus) to
 control your audio devices.
 
-## A note about PulseAudio, DBus and Awesome
-
-The Pulseaudio DBus interface requires clients to use peer-to-peer connection
-rather than the usual system/session buses. This means that we *cannot* use the
-Awesome DBus API that supports *only* system and session buses.
-
-The solution is to run an external client application to establish a
-peer-to-peer connection and listen to DBus signals. The output of the client is
-read by the widget that updates itself accordingly. This is done thanks
-to
-[`awful.spawn.with_line_callback`](https://awesomewm.org/apidoc/libraries/awful.spawn.html#with_line_callback).
-
 # Requirements
 
 In addition to the requirements listed in the `rockspec` file, you will need
diff --git a/pulseaudio_widget.lua b/pulseaudio_widget.lua
index 8af9acb..df30cf6 100644
--- a/pulseaudio_widget.lua
+++ b/pulseaudio_widget.lua
@@ -29,6 +29,7 @@ local beautiful = require("beautiful")
 local naughty = require("naughty")
 
 local pulse = require("pulseaudio_dbus")
+local GLib = require("lgi").GLib
 
 local icon_theme = "/usr/share/icons/Adwaita/scalable/status"
 local icon_extension = ".svg"
@@ -125,9 +126,12 @@ function widget.toggle_muted_mic()
 end
 
 function widget:kill_client()
+  -- FIXME: This does not work without a "worker child process"
+  --[[
   if type(self.server_pid) == "number" then
     awful.spawn("kill -TERM " .. self.server_pid)
   end
+  --]]
 end
 
 function widget:run_client()
@@ -146,9 +150,8 @@ function widget:run_client()
     end
   end
 
-  local pid = awful.spawn.with_line_callback(
-    [[lua -e 'require("pulseaudio_widget_client")']],
-    {
+
+  require("pulseaudio_widget_client")(function (line)
     stdout = function (line)
 
       update_after_signal(line, "^(VolumeUpdated:%s+)(%d+)(|)([%w/]+)", "%2 %4")
@@ -169,9 +172,7 @@ function widget:run_client()
         self:update_source({v})
       end
     end
-  })
-
-  self.server_pid = pid
+  )
 end
 
 widget:buttons(gears.table.join(
diff --git a/pulseaudio_widget_client.lua b/pulseaudio_widget_client.lua
index fb628f4..6d2b8f6 100644
--- a/pulseaudio_widget_client.lua
+++ b/pulseaudio_widget_client.lua
@@ -32,6 +32,7 @@
 local pulse = require("pulseaudio_dbus")
 local GLib = require("lgi").GLib
 
+return function(print)
   local address = pulse.get_address()
 
   local connection = pulse.get_connection(address)
@@ -107,4 +108,6 @@ core:connect_signal(
 
   -- Start the client. Send SIGTERM to stop it.
   print("Starting Awesome PulseAudio Widget Client")
-GLib.MainLoop():run()
+
+  --GLib.MainLoop():run()
+end
```
That's the best I can offer right now, sorry.

**Comment by stefano-m** [comment]
@psychon thank you very much for the suggestion and the sample code. It was very useful to get my head around what needed to be done.

I have published a new version of the widget that works without a child process.

Regarding the awesome recipes, I'd be happy to contribute. I'll try and have a look at it at some point.
