### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by tasmo** [stefano-m/awesome-pulseaudio_widget#10]
Because it as a GUI widget I would like to see one or more examples before installing it.

**Comment by stefano-m** [comment]
Hello,

as the README says:

> The widget will display the audio icons defined in your GTK+ theme and it will resize them to fit in the available space. This means that you can switch your icon theme, for example using lxappearance, and update the widget by restarting AwesomeWM.

So it really depends on the icon set you use.

**Comment by stefano-m** [comment]
Closing for lack of response.
