### ISSUE TITLE
Error with pipewire-pulse

### ISSUE THREAD

**Issue by aspieln3r** [stefano-m/awesome-pulseaudio_widget#11]
I'm using pipewire-pulse as a pulseaudio replacement end everything inclding pavucontrol works as expected except awesome-pulseaudio_widget . On startup, I get this GDBus service unknown error. 
` The name org.Pulseaudio1 was not provided by any .service files ` . 

`Linux s510u 5.4.85-1-lts #1 SMP Mon, 21 Dec 2020 19:28:35 +0000 x86_64 GNU/Linux`
I'm using archlinux

**Comment by stefano-m** [comment]
Hello,

this widget talks to [pulseaudio's DBus Interface](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/). If pipewire does not support it (which seems the case given the error you see), I'm afraid that the widget won't work for you.
