### ISSUE TITLE
Adding new commands to switch `FallbackSink` and move `PlaybackStream`s?

### ISSUE THREAD

**Issue by doronbehar** [stefano-m/awesome-pulseaudio_widget#3]
Hello again @stefano-m,

Since https://github.com/stefano-m/lua-pulseaudio_dbus/commit/4a62266b14a6ef007a713465ab69b37dd8eea9ae, I thought to myself it may be proper that we will add functions such is `next_FallbackSink` and `move_PlaybackStreams_to_FallbackSink`. Those functions could mimic the same actions in the last two tests added in the commit above ([`lua-pulseaudio_dbus/tests/pulseaudio_dbus_spec.lua#L168`](https://github.com/stefano-m/lua-pulseaudio_dbus/blob/4a62266b14a6ef007a713465ab69b37dd8eea9ae/tests/pulseaudio_dbus_spec.lua#L168) and [`lua-pulseaudio_dbus/tests/pulseaudio_dbus_spec.lua#L183`](https://github.com/stefano-m/lua-pulseaudio_dbus/blob/4a62266b14a6ef007a713465ab69b37dd8eea9ae/tests/pulseaudio_dbus_spec.lua#L183))

I'm not sure what would be proper, adding these functions to the library (`pulseaudio_dbus`) or to add it to this widget or perhaps even go further and make it only a suggestion in the documentation for users to add such functions to their `rc.lua`?
Thanks!

**Comment by stefano-m** [comment]
Hi,

can you please explain a use case for this? How would you use the functions?

If there is a valuable use case, my feeling is that this change should be implemented in the `pulseaudio_dbus` library and then propagated to the widget.

**Comment by doronbehar** [comment]
First of all, it's great to hear back from you after all this time.

I've started this discussion here and in [`pulseaudio_dbus`](https://github.com/stefano-m/lua-pulseaudio_dbus/issues?q=author:doronbehar) because I need this functionality on my machine and I felt it is missing in this AwesomeWM widget not to mention many other pulseaudio widgets like [vicious'](https://github.com/Mic92/vicious/blob/master/contrib/pulse_all.lua) and [lain's](https://github.com/lcpz/lain/wiki/pulse#keybindings) pulseaudio widgets.

On modern Linux desktop environments like GNOME there is a built in mechanism for managing pulseaudio. It includes functionality as suggested in this issue. I haven't used GNOME in a while now but I remember that when I did I had configurable keyboard shortcuts for **fully** switching output sinks. By that I mean switching the default sink **and** moving the playback streams  to the new default sink.

Since I realised this is not so obvious if one uses strictly the command line or a window manager's keyboard shortcuts mapped to shell commands like [these](https://github.com/orofarne/pulseaudio-awesome/blob/master/pulseaudio.lua), I wanted to implement it my self with a faster approach taken with dbus interface like you chose to use in this widget and through [`pulseaudio_dbus`](https://github.com/stefano-m/lua-pulseaudio_dbus).

BTW, here is a [question on askubuntu.com](https://askubuntu.com/q/71863) asking for help regarding pulseaudio commands that switch the default sink.

**Comment by stefano-m** [comment]
Basically the functionality would be something that would allow one to plug in a new sink (e.g. an HDMI monitor) and then transfer all the streams (e.g. some music playing and a youtube video) to that sink.

Do I understand correctly?

If that's the case I think we could add the functions to the library and then propagate it to the widget.

I would probably let the user to decide whether they want to add it to their configuration (e.g. with a keyboard shortcut).

Another possibility would be to listen to some event and do the switch automatically (this would happen in the widget code, using the functions from the library). Which is something that would probably be useful (although I would make it optional).

**Comment by doronbehar** [comment]
Correct. I hope that once we finish [`pulseaudio_dbus`' issues](https://github.com/stefano-m/lua-pulseaudio_dbus/issues?q=author:doronbehar%20is:open) we can start work on the widget's new functions and hopefully release a new version.

I'll get back to those as soon as I land on my computer.

**Comment by stefano-m** [comment]
@doronbehar I was wondering whether pulseaudio's `module-switch-on-connect` would help you anyway:

> module-switch-on-connect
>
> Whenever a new sink or source appears, this module will switch the default sink/source to be the new sink/source, and will move all currently running streams to the new sink/source.
>
>    only_from_unavailable
>        Takes a boolean value. If set to true, the device switch is only done if the current default device is currently marked as unavailable.

https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/

**Comment by doronbehar** [comment]
I was thinking about it but the problem is that if I connect a new sink, this module won't switch back to the original default sink for me when I disconnect the newer sink. I tested it with a git version of pulseaudio compiled from source.

**Comment by stefano-m** [comment]
Closing for lack of feedback. Can be reopened if the discussion starts again.
