### ISSUE TITLE
Error: "attempt to index a nil value (local 'bus')"

### ISSUE THREAD

**Issue by DanielVartanov** [stefano-m/awesome-pulseaudio_widget#6]
The aforementioned error is fired on `require("pulseaudio_widget")`.
AwesomeWM 4.2
Lua 5.3
pulseaudio_widget was installed via luarocks

I am happy to provide any additional info which would help to resolve the issue.
Thanks in advance.

**Comment by stefano-m** [comment]
Well, that message means that pulseaudio did not find any outputs (they call them "sinks").

You can try to run `pavucontrol` from the terminal and check whether there are any outputs defined in the "Output Devices" tab.

I'm not sure I can help you any further than this.

**Comment by stefano-m** [comment]
The line that causes the error is:

https://github.com/stefano-m/awesome-pulseaudio_widget/blob/fbb711bac3a4dc0c266db96d61addc8ba93791e8/pulseaudio_widget.lua#L217

All it does is to check whether there are any sinks (i.e. outputs) defined by pulseaudio. If there's nothing, it throws an error to signal it to the end user. But in the end this should be a problem with pulseaudio, not the widget itself.

**Comment by DanielVartanov** [comment]
OK, right it seems to be a local problem with my pulseaudio, not with pulseaudio_widget.
Thanks a lot for your help!
